// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigwKm4qYPuhoq0KlVORfByTHhD2O-o1I',
    appId: '1:745503800412:web:a304e935d53e967a48ba99',
    messagingSenderId: '745503800412',
    projectId: 'instagram-clone-beed8',
    authDomain: 'instagram-clone-beed8.firebaseapp.com',
    storageBucket: 'instagram-clone-beed8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqCTNgrPMe0qV663GLyg2d8rgCUICrKE',
    appId: '1:745503800412:android:74e7adb632870bd148ba99',
    messagingSenderId: '745503800412',
    projectId: 'instagram-clone-beed8',
    storageBucket: 'instagram-clone-beed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZkkkhxTYVIaycpLStzZuG_F_DuweNPo',
    appId: '1:745503800412:ios:8a6a4a9f33b069fa48ba99',
    messagingSenderId: '745503800412',
    projectId: 'instagram-clone-beed8',
    storageBucket: 'instagram-clone-beed8.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );
}
